/*
 * File: app/view/Escritorio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.Escritorio', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.escritorio',

    requires: [
        'signeGeoportal.view.EscritorioViewModel',
        'signeGeoportal.view.ListaLayer',
        'signeGeoportal.view.ContentPanel',
        'signeGeoportal.view.LegendPanel',
        'signeGeoportal.view.InfoPanel',
        'signeGeoportal.view.MapPanel',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'escritorio'
    },
    id: 'escritorio',
    itemId: 'myviewport',
    padding: '10 10 10',

    layout: {
        type: 'border',
        padding: ''
    },
    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'contenedorOpcion',
            margin: '0 0 5 0',
            width: 400,
            layout: 'accordion',
            collapseDirection: 'left',
            collapsible: true,
            hideCollapseTool: true,
            titleCollapse: true,
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top',
                    html: '<div class="logo-empresa"></div>',
                    id: 'contenedorLogo'
                }
            ],
            items: [
                {
                    xtype: 'listalayer'
                },
                {
                    xtype: 'contentpanel'
                },
                {
                    xtype: 'legendpanel'
                },
                {
                    xtype: 'infopanel'
                }
            ]
        },
        {
            xtype: 'container',
            region: 'center',
            itemId: 'contenedorPrincipal',
            margin: '0 0 5 0',
            layout: 'fit',
            items: [
                {
                    xtype: 'mappanel'
                }
            ]
        }
    ]

});