/*
 * File: app/view/InfoPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.InfoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.infopanel',

    requires: [
        'signeGeoportal.view.InfoPanelViewModel'
    ],

    viewModel: {
        type: 'infopanel'
    },
    height: '100%',
    padding: '',
    width: '100%',
    layout: 'fit',
    title: 'Información de elementos',
    titleAlign: 'center'

});