/*
 * File: app/view/MapPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.Legend', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.legend',

    requires: [
		'GeoExt.tree.Panel',
		'Ext.tree.plugin.TreeViewDragDrop',
		'GeoExt.panel.Map',
		'GeoExt.tree.OverlayLayerContainer',
		'GeoExt.tree.BaseLayerContainer',
		'GeoExt.data.LayerTreeModel',
		'GeoExt.tree.View',
		'GeoExt.container.WmsLegend',
		'GeoExt.tree.Column',
		// We need to require this class, even though it is used by Ext.EventObjectImpl
		// see: http://www.sencha.com/forum/showthread.php?262124-Missed-(-)-dependency-reference-to-a-Ext.util.Point-in-Ext.EventObjectImpl
		'Ext.util.Point'
    ],

    id: 'Legend',
    layout: 'fit',
	height: 300,

    initComponent: function() {
        var me = this,
		items = [];

        var tree = Ext.create('GeoExt.tree.Panel', {
            region: "center",
            title: "Layers",
			height: 300,
            width: 250,
            autoScroll: true,
            viewConfig: {
                plugins: [{
                    ptype: 'treeviewdragdrop',
                    appendOnly: false
                }]
            },
            store: signeGeoportal.xLayerStore,
            rootVisible: false,
            lines: false
        });
		
		console.log(signeGeoportal.xLayerStore);

		items.push(tree);
	
	Ext.apply(me, {
          items: items
			});
		me.callParent(arguments);
	}
});