/*
 * File: app/view/ListaLayer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.ListaLayer', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.listalayer',

    requires: [
        'signeGeoportal.view.ListaLayerViewModel',
        'signeGeoportal.view.ListaLayerViewController',
        'Ext.grid.filters.filter.String',
        'Ext.toolbar.Toolbar',
        'Ext.grid.column.Action',
        'Ext.grid.filters.Filters'
    ],

    controller: 'listalayer',
    viewModel: {
        type: 'listalayer'
    },
    height: '100%',
    id: '',
    itemId: '',
    width: '100%',
    title: 'Explorador de capas',
    titleAlign: 'center',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'title',
            text: 'Titulo',
            flex: 0.7,
            filter: {
                type: 'string',
                emptyText: 'Escriba el título de la capa...'
            }
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'abstract',
            text: 'Descripción',
            flex: 0.3
        },
        {
            xtype: 'actioncolumn',
            id: 'acMetadata',
            width: 30,
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        //console.log(record);

                        if (signeGeoportal.xTip) {
                            signeGeoportal.xTip.destroy();
                            signeGeoportal.xTip = null;
                        }

                        signeGeoportal.xTip = window.Ext.create('Ext.tip.ToolTip', {
                            title: '<h3><font color="#08298A">'+record.data.title+'</font></h3>',
                            //title: '<a href="#">'+record.data.title+'</a>',
                            id: 'content-anchor-tip',
                            target: 'acMetadata',
                            anchor: 'left',
                            html: '<ul><li><font color="#013ADF"><b><u>Descripción: </u></b></font>'+ record.data.abstract +
                            '</li><br><li><font color="#013ADF"><b><u>Nombre : </u></b></font>'+record.data.name+'</li><br>' +
                            '<li><font color="#013ADF"><b><u>Enlace WMS: </u></b></font>'+record.data.url+'</li></ul></font>',
                            width: 415,
                            autoShow:true,
                            autoHide: false,
                            closable: true,
                            stateful: false,
                            dismissDelay: 10000,
                            //contentEl: 'content-tip', // load content from the page
                            listeners: {
                                /*'render': function(){
                                this.header.on('click', function(header, e){
                                e.stopEvent();
                                Ext.Msg.alert('Link', 'Link to something interesting.');
                                Ext.getCmp('content-anchor-tip').hide();
                                }, this, {delegate:'a'});
                                },*/
                                'hide': function () {
                                    signeGeoportal.xTip.destroy();
                                    signeGeoportal.xTip = null;
                                }
                            }
                        });

                        // show immediately
                        signeGeoportal.xTip.show();



                    },
                    getTip: function(value, metadata, record, row, col, store) {
                        return 'Ver metadata';
                    },
                    iconCls: 'help-icon'
                }
            ]
        },
        {
            xtype: 'actioncolumn',
            id: 'acOpcion',
            width: 30,
            items: [
                {
                    handler: 'aniadir',
                    altText: 'Añadir Capa',
                    iconCls: 'add-file-icon',
                    tooltip: 'Añadir capa al mapa'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            id: 'toolListaLayer'
        }
    ],
    plugins: [
        {
            ptype: 'gridfilters',
            pluginId: 'gfListaLayer',
            menuFilterText: 'Filtrar'
        }
    ]

});