/*
 * File: app/view/ListaLayerViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.ListaLayerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.listalayer',

    aniadir: function(view, rowIndex, colIndex, item, e, record, row) {

        var clone = record.clone();

        //console.log(clone.data);

        var storeParametro = Ext.StoreMgr.lookup("storeParametro");

        storeParametro.getProxy().setExtraParam("nombre_capa", record.data.name);

        storeParametro.load(function(records, operation, success) {

            if (this.getCount()>=1){
                signeGeoportal.xClone = clone.data;

                var windowParametro= Ext.widget('ventanaparametro');
                windowParametro.setTitle("Seleccione el(los) parámetro(s) de la capa " + record.data.title);
                windowParametro.show();
            }else{
                signeGeoportal.getApplication().aniadarCapa(record.data.title, record.data.url, record.data.name, clone.data, null, null);
            }
        });

        //console.log(record.data);
    }

});
