/*
 * File: app/view/MapPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.MapPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mappanel',

    requires: [
        'signeGeoportal.view.MapPanelViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    config: {
        items: {
            xtype: 'map',
            region: 'center'
        }
    },

    viewModel: {
        type: 'mappanel'
    },
    margin: '',
    width: '',
    layout: 'fit',
    title: '',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            itemId: 'barraHerramientas',
            items: [
                {
                    xtype: 'button',
                    id: 'btnEnfocar',
                    iconAlign: 'top',
                    iconCls: 'zoom-extent',
                    scale: 'medium',
                    text: 'Enfocar país',
                    tooltip: 'Enfocar al país'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {
                        if (state === true){
                            signeGeoportal.xInfo.activate();
                        }else{
                            signeGeoportal.xInfo.deactivate();
                        }

                    },
                    id: 'btnInformacion',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'info',
                    scale: 'medium',
                    text: 'Información',
                    tooltip: 'Información de elementos'
                },
                {
                    xtype: 'button',
                    id: 'btnImprimir',
                    iconAlign: 'top',
                    iconCls: 'print',
                    scale: 'medium',
                    text: 'Imprimir',
                    tooltip: 'Imprimir mapa'
                },
                {
                    xtype: 'button',
                    id: 'btnAyuda',
                    iconAlign: 'top',
                    iconCls: 'help-icon1',
                    scale: 'medium',
                    text: 'Ayuda',
                    tooltip: 'Ayuda'
                }
            ]
        }
    ]

});