/*
 * File: app/view/MapPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.MapPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mappanel',

    requires: [
        'signeGeoportal.view.MapPanelViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    config: {
        items: {
            xtype: 'map',
            region: 'center'
        }
    },

    viewModel: {
        type: 'mappanel'
    },
    margin: '',
    width: '',
    layout: 'fit',
    title: '',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            itemId: 'barraHerramientas',
            items: [
                {
                    xtype: 'button',
                    id: 'btnEnfocar',
                    iconAlign: 'top',
                    iconCls: 'zoom-extent',
                    scale: 'medium',
                    text: 'Enfocar',
                    tooltip: 'Enfocar al país'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {
                        Ext.getCmp("lineToggle").toggle(false);
                        Ext.getCmp("polygonToggle").toggle(false);
                        Ext.getCmp("btnInformacion").toggle(false);
                        Ext.getCmp("btnPosicion").toggle(false);

                        signeGeoportal.getApplication().toggleControl(this);
                    },
                    id: 'btnNavegar',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'hand-icon',
                    pressed: true,
                    scale: 'medium',
                    text: 'Navegar',
                    tooltip: 'Enfocar al país'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {
                        Ext.getCmp("btnNavegar").toggle(false);
                        Ext.getCmp("polygonToggle").toggle(false);
                        Ext.getCmp("btnInformacion").toggle(false);
                        Ext.getCmp("btnPosicion").toggle(false);

                        var infopanel = Ext.ComponentQuery.query('infopanel')[0];
                        infopanel.expand();

                        signeGeoportal.getApplication().toggleControl(this);

                    },
                    id: 'lineToggle',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'rule-icon',
                    scale: 'medium',
                    text: 'Distancia',
                    tooltip: 'Información de elementos'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {
                        Ext.getCmp("btnNavegar").toggle(false);
                        Ext.getCmp("lineToggle").toggle(false);
                        Ext.getCmp("btnInformacion").toggle(false);
                        Ext.getCmp("btnPosicion").toggle(false);


                        var infopanel = Ext.ComponentQuery.query('infopanel')[0];
                        infopanel.expand();

                        signeGeoportal.getApplication().toggleControl(this);

                        /*var infopanel = Ext.ComponentQuery.query('infopanel')[0];

                        if (state === true){

                        infopanel.expand();

                        signeGeoportal.xMeasure.activate();
                        }else{
                        //infopanel.collapse();

                        signeGeoportal.xMeasure.deactivate();
                    }*/

                    },
                    id: 'polygonToggle',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'tape-icon',
                    scale: 'medium',
                    text: 'Area',
                    tooltip: 'Información de elementos'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {

                        Ext.getCmp("btnNavegar").toggle(false);
                        Ext.getCmp("lineToggle").toggle(false);
                        Ext.getCmp("polygonToggle").toggle(false);
                        Ext.getCmp("btnInformacion").toggle(false);

                        var infopanel = Ext.ComponentQuery.query('infopanel')[0];

                        infopanel.expand();

                        signeGeoportal.getApplication().toggleControl(this);

                        /*if (state === true){
                        signeGeoportal.xInfo.activate();
                        }else{
                        signeGeoportal.xInfo.deactivate();
                        }*/

                    },
                    id: 'btnPosicion',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'pos-icon',
                    scale: 'medium',
                    text: 'Posición',
                    tooltip: 'Información de elementos'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    toggleHandler: function(button, state) {

                        Ext.getCmp("btnNavegar").toggle(false);
                        Ext.getCmp("lineToggle").toggle(false);
                        Ext.getCmp("polygonToggle").toggle(false);
                        Ext.getCmp("btnPosicion").toggle(false);


                        signeGeoportal.getApplication().toggleControl(this);

                        /*if (state === true){
                        signeGeoportal.xInfo.activate();
                        }else{
                        signeGeoportal.xInfo.deactivate();
                        }*/

                    },
                    id: 'btnInformacion',
                    enableToggle: true,
                    iconAlign: 'top',
                    iconCls: 'info',
                    scale: 'medium',
                    text: 'Info',
                    tooltip: 'Información de elementos'
                },
                {
                    xtype: 'button',
                    id: 'btnImprimir',
                    iconAlign: 'top',
                    iconCls: 'print',
                    scale: 'medium',
                    text: 'Imprimir',
                    tooltip: 'Imprimir mapa'
                },
                {
                    xtype: 'button',
                    id: 'btnAyuda',
                    iconAlign: 'top',
                    iconCls: 'help-icon1',
                    scale: 'medium',
                    text: 'Ayuda',
                    tooltip: 'Ayuda'
                }
            ]
        }
    ]

});