/*
 * File: app/view/VentanaParametro.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.VentanaParametro', {
    extend: 'Ext.window.Window',
    alias: 'widget.ventanaparametro',

    requires: [
        'signeGeoportal.view.VentanaParametroViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'ventanaparametro'
    },
    border: false,
    height: 231,
    id: 'VentanaParametro',
    width: 400,
    title: 'Parametros de capa',
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            height: 200,
            itemId: 'mygridpanel',
            width: 400,
            manageHeight: false,
            title: '',
            store: 'storeParametro',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'descripcion',
                    text: 'Descripción',
                    flex: 1
                }
            ]
        }
    ]

});