/*
 * File: app/view/VentanaParametro.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.VentanaParametro', {
    extend: 'Ext.window.Window',
    alias: 'widget.ventanaparametro',

    requires: [
        'signeGeoportal.view.VentanaParametroViewModel',
        'Ext.grid.property.Grid',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'ventanaparametro'
    },
    border: false,
    height: 325,
    id: 'VentanaParametro',
    width: 473,
    layout: 'border',
    title: 'Parametros de capa',
    modal: true,

    items: [
        {
            xtype: 'propertygrid',
            region: 'center',
            id: 'pgParametro',
            title: ''
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnAniadirCapa',
                    iconCls: 'add-file-icon',
                    text: 'Añadir'
                }
            ]
        }
    ]

});