/*
 * File: app/view/VistaPrevia.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.view.VistaPrevia', {
    extend: 'Ext.window.Window',
    alias: 'widget.vistaprevia',

    requires: [
        'signeGeoportal.view.VistaPreviaViewModel',
        'Ext.Component'
    ],

    viewModel: {
        type: 'vistaprevia'
    },
    height: 600,
    width: 800,
    layout: 'border',
    title: 'Visor de documento',
    modal: true,

    items: [
        {
            xtype: 'component',
            region: 'center',
            id: 'vistaPrevia'
        }
    ]

});