/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        GeoExt: '../geoext2210/src/GeoExt'
    }
});


Ext.application({

    requires: [
        'Ext.Loader'
    ],
    views: [
        'Escritorio',
        'LegendPanel',
        'MapPanel',
        'Map',
        'ListaLayer',
        'InfoPanel',
        'ContentPanel'
    ],
    controllers: [
        'controllerMapa'
    ],
    name: 'signeGeoportal',

    launch: function() {
        Ext.create('signeGeoportal.view.Escritorio');
        // Carga el listado de capas disponibles en el servidor

        var store = Ext.create('GeoExt.data.WmsCapabilitiesLayerStore', {
            storeId: 'wmscapsStore',
            url: "http://192.168.56.2:8080/geoserver/SIGE/wms?service=wms&version=1.1.1&request=GetCapabilities",
            autoLoad: true
        });

        var grid = Ext.ComponentQuery.query('listalayer')[0];

        grid.reconfigure(store);

        // Define y crea el panel de leyenda

        signeGeoportal.xLayerStore = Ext.create('Ext.data.TreeStore', {
            model: 'GeoExt.data.LayerTreeModel',
            root: {
                plugins: [{
                    ptype: "gx_layercontainer",
                    /*loader: {
                        createNode: function(attr) {
                            // add a WMS legend to each node created
                            attr.component = {
                                xtype: "gx_wmslegend",
                                layerRecord: signeGeoportal.xMap.layers.getByLayer(attr.layer),
                                showTitle: false,
                                // custom class for css positioning
                                // see tree-legend.html
                                cls: "legend"
                            };
                            return GeoExt.tree.LayerLoader.prototype.createNode.call(this, attr);
                        }
                    }*/
                }]
            }
        });


        var treeLayer = Ext.create('GeoExt.tree.Panel', {
            region: "center",
            autoScroll: true,
            id: 'treelayer',
            viewConfig: {
                plugins: [{
                    ptype: 'treeviewdragdrop',
                    appendOnly: false
                }]
            },
            store: signeGeoportal.xLayerStore,
            rootVisible: false,
            lines: false
        });

        //*** Este código añade al panel el arbol que contiene los layers y la leyenda
        var contentpanel = Ext.ComponentQuery.query('contentpanel')[0];
        contentpanel.add(treeLayer);

        var legendLayer = Ext.create('GeoExt.panel.Legend',{
            region: "center",
            autoScroll: true,
            id: 'legendlayer',
            padding: 5,
            layerStore: signeGeoportal.xMap.layers
        });

        var legendpanel = Ext.ComponentQuery.query('legendpanel')[0];

        //*** Este código añade al panel el arbol que contiene los layers y la leyenda
        legendpanel.add(legendLayer);

        // Define y crea el panel de información

        signeGeoportal.xInfo = new OpenLayers.Control.WMSGetFeatureInfo({
            //    autoActivate: true,
            infoFormat: "application/vnd.ogc.gml",
            maxFeatures: 3,
            eventListeners: {
                "getfeatureinfo": function(e) {
                    var items = [];

                    var infopanel = Ext.ComponentQuery.query('infopanel')[0];

                    infopanel.removeAll();
                    //infopanel.remove('infogrid',false);

                    Ext.each(e.features, function(feature) {

                        var propiedades = Ext.create('Ext.grid.property.Grid', {
                            title: feature.fid,
                            nameColumnWidth: '60%',
                            source: feature.attributes,
                            heigth:200,
                        });

                        propiedades.columns[0].setText('Propiedad');
                        propiedades.columns[1].setText('Valor');

                        items.push(propiedades);
                    });

                    infopanel.add(items);

                    /*var popup = Ext.create('GeoExt.window.Popup', {
                        title: "Feature Info",
                        width: 300,
                        height: 300,
                        layout: "accordion",
                        map: signeGeoportal.xMap,
                        location: e.xy,
                        items: items
                    });

                    popup.show();*/


                }
            }
        });

        signeGeoportal.xMap.map.addControl(signeGeoportal.xInfo);

    },

    aniadarCapa: function(titulo_capa, url_capa, nombre_capa) {
        var wms = new OpenLayers.Layer.WMS(
            titulo_capa,
            url_capa,
            {layers:nombre_capa,
             transparent : 'true',
             format: 'image/png'
            },
            {opacity: 0.8,
             isBaseLayer: false,
             //     attribution: "<img src='"+url_capa+"request=GetLegendGraphic&format=image/png&width=18&height=17&layer="+nombre_capa+"&legend_options=fontName:Times%20New%20Roman;fontAntiAliasing:true;fontColor:0x000033;fontSize:12;bgColor:0xFFFFEE;dpi:180'>"
            }
        );

        signeGeoportal.xMap.map.addLayer(wms);
    }

});
