/*
 * File: app/controller/controllerMapa.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.controller.controllerMapa', {
    extend: 'Ext.app.Controller',

    views: [
        'LegendPanel'
    ],

    control: {
        "#btnEnfocar": {
            click: 'onBtnEnfocarClick'
        },
        "#btnEliminarCapa": {
            click: 'onBtnEliminarCapaClick'
        },
        "#btnImprimir": {
            click: 'onBtnImprimirClick'
        }
    },

    onBtnEnfocarClick: function(button, e, eOpts) {
        signeGeoportal.xMap.map.zoomToScale(2000000,false);

        //signePortal.xMap.zoomToExtent(new OpenLayers.Bounds(minLng,minLat,maxLng,maxLat));
    },

    onBtnEliminarCapaClick: function(button, e, eOpts) {
        var layer = signeGeoportal.getApplication().obtenerLayer();

        if (layer){
            Ext.MessageBox.show({
                title : 'Eliminar Capa',
                buttons : Ext.MessageBox.YESNO,
                msg : 'Realmente desea eliminar la capa ' + record.data.layer.name +  ' del mapa ?',
                icon : Ext.Msg.WARNING,
                fn : function(btn)
                {
                    if (btn == 'yes')
                    {
                        signeGeoportal.xMap.map.removeLayer(layer);
                    }

                }
            });
        }



    },

    onBtnImprimirClick: function(button, e, eOpts) {
        /*** Funcional ****/
        /*printDialog = Ext.create('Ext.Window', {
            title: "Vista previa de impresión",
            layout: "fit",
            border: false,
            width: 500,
            modal: true,
            heigth: 200,
            // autoHeight: true,
            items: [{
                xtype: 'textfield',
                fieldLabel: 'Titulo',
                id: 'txtTitulo',
                width: 200,
                height: 10,
                //  anchor: '90%',
            },{
                xtype: "gx_printmappanel",
                sourceMap: signeGeoportal.xMap,
                printProvider: printProvider,
            },
                    {
                        xtype: 'textarea',
                        fieldLabel: 'Comentario',
                        id: 'txtComentario',
                        width: 100,
                        //        anchor: '90%',
                    }],
            tbar: [{
                text: "Imprimir PDF",
                handler: function(){
                    printDialog.items.get(1).printProvider.customParams.mapTitle = Ext.getCmp('txtTitulo').getValue();
                    printDialog.items.get(1).printProvider.customParams.comment = Ext.getCmp('txtComentario').getValue();
                    printDialog.items.get(1).print();
                }
            }]
        });

        printDialog.show();*/

        printDialog = Ext.create('Ext.Window', {
            height: 580,
            width: 650,
            layout: 'border',
            title: 'Vista previa de impresión.',
            modal: true,
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 160,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnImprimirMapa',
                                    text: 'Imprimir PDF',
                                    handler: function(){
                                        var legendpanel = Ext.getCmp('legendlayer');
                                        //console.log();


                                        var includeLegend;
                                        includeLegend = true;
                                        printPage.scale = 100000;
                                        printPage.fit(signeGeoportal.xMap, true);

                                        printDialog.items.get(1).items.get(0).printProvider.customParams.mapTitle = Ext.getCmp('txtTitulo').getValue();
                                        printDialog.items.get(1).items.get(0).printProvider.customParams.comment = Ext.getCmp('txtComentario').getValue();
                                        printDialog.items.get(1).items.get(0).print(signeGeoportal.xMap, printPage, includeLegend && {legend: legendpanel});

                                        // convenient way to fit the print page to the visible map area
                                        //printPage.fit(mapPanel, true);
                                        // print the page, optionally including the legend
                                        //printProvider.print(mapPanel, printPage, includeLegend && {legend: legendPanel});
                                    }

                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Información del mapa',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'txtTitulo',
                                    fieldLabel: 'Titulo',
                                    name: 'tituloMapa',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'txtComentario',
                                    fieldLabel: 'Comentario',
                                    name: 'comentarioMapa',
                                    allowBlank: false
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    items: {
                        xtype: "gx_printmappanel",
                        sourceMap: signeGeoportal.xMap,
                        printProvider: printProvider,
                        zoom: 10,
                        limitScales:false
                    },
                    region: 'center',
                    layout: 'fit',
                }]
        });

        printDialog.show();
    }

});
