/*
 * File: app/controller/controllerLogin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('signeGeoportal.controller.controllerLogin', {
    extend: 'Ext.app.Controller',

    stores: [
        'storeLogin'
    ],

    refs: {
        escritorio: 'Escritorio'
    },

    control: {
        "#btnIngreso": {
            click: 'onBtnIngresoClick'
        },
        "#btnSalir": {
            click: 'onBtnSalirClick'
        },
        "#WindowLogin": {
            afterrender: 'onWindowLoginAfterRender'
        }
    },

    onBtnIngresoClick: function(button, e, eOpts) {
        var win = button.up('window');
        form = win.down('form');

        if (form.getForm().isValid()) {
            win.mask("Ingresando al sistema...");

            var user = form.down('#usuario').getValue();
            var pwd = form.down('#pass').getValue();

            store = this.getStoreLoginStore();

            store.getProxy().setExtraParam('user', user);
            store.getProxy().setExtraParam('pwd', pwd);

            store.load(function(records, operation, success) {
                if(this.getCount()>=1){


                    indice = store.getAt(0);

                    win.close();

                    var escritorio= Ext.widget('escritorio');
                    escritorio.show();

                    statusBar = escritorio.down('#statusBar');
                    statusBar.items.getAt(0).update('Usuario activo: ' + indice.get('usuario'));

                }
                else{
                    win.unmask();

                    Ext.MessageBox.show({
                        title: 'Mensaje del Sistema',
                        msg: 'Los datos de usuario que se proporcionarón son inválidos.',
                        icon: Ext.MessageBox.ERROR,
                        buttons: Ext.Msg.OK
                    });
                }

            });

        }
    },

    onBtnSalirClick: function(button, e, eOpts) {
        this.salir();
    },

    onWindowLoginAfterRender: function(component, eOpts) {
        if (Ext.get('loading')) {
            Ext.get('loading').remove();
        }
    },

    salir: function() {

        var escritorio= Ext.getCmp('escritorio');

        escritorio.destroy();

        var windowLogin= Ext.widget('clslogin');

        windowLogin.show();
    }

});
